<?php
namespace common\models;

use common\components\ActiveRecord;
use common\components\PhotoThumbBehavior;
use common\models\interfaces\IImageModel;
use FilesystemIterator;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use Yii;
use yii\base\ErrorException;
use yii\helpers\ArrayHelper;

/**
 * Class JournalPhoto
 * @package common\models
 *
 * @property integer $id
 * @property integer $journal_id
 * @property string $photo
 * @property string $description
 * @property integer $status
 * @property integer $updated_at
 * @property Journal $journal
 * @property boolean $isOnCloud
 * @mixin PhotoThumbBehavior
 */
class JournalPhoto extends ActiveRecord implements IImageModel
{
    const STATUS_DRAFT = 1;
    const STATUS_ON_CHECK = 2;
    const STATUS_PUBLISHED = 3;

    public function getJournal()
    {
        return $this->hasOne(Journal::className(), ['id' => 'journal_id'])->inverseOf('photos');
    }

    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                'PhotoThumbBehavior' => [
                    'class' => PhotoThumbBehavior::className(),
                ],
            ]
        );
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return [
            ['photo', 'filter', 'filter' => 'trim'],
            ['photo', 'required'],
            ['photo', 'string', 'min' => 3, 'max' => 255],
            ['description', 'string', 'max' => 400],
        ];
    }

    public function beforeValidate()
    {
        $this->description = str_replace("\r", "", $this->description);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function scenarios() {
        $scenarios = parent::scenarios();
        $scenarios['create'] = ['photo'];
        $scenarios['update'] = ['photo'];
        return $scenarios;
    }

    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'journal_id' => 'Дневник',
            'photo' => 'Фото',
            'updated_at' => 'Последнее обновление',
            'status' => 'Статус',
            'description' => 'Описание фотографии',
        );
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        if ($insert && file_exists(self::getTempPath().'/'.$this->photo))
            if (!rename(self::getTempPath().'/'.$this->photo, self::getPath().'/'.$this->photo)) {
                throw new ErrorException("Ошибка при сохранении фото [1]");
            }
    }

    public function afterDelete()
    {
        if (file_exists($this->getPhotoThumbPath()) and is_dir($this->getPhotoThumbPath())) {
            $di = new RecursiveDirectoryIterator($this->getPhotoThumbPath(), FilesystemIterator::SKIP_DOTS);
            $ri = new RecursiveIteratorIterator($di, RecursiveIteratorIterator::CHILD_FIRST);
            foreach ($ri as $file) {
                $file->isDir() ?  rmdir($file) : unlink($file);
            }
            rmdir($this->getPhotoThumbPath());
        }

        if (file_exists(self::getPath().'/'.$this->photo)) {
            unlink(self::getPath().'/'.$this->photo);
        }
        parent::afterDelete();
    }

    public function getPhotoUrl()
	{
		if ($this->isOnCloud) {
			return Yii::$app->s3bucket->getPresignedUrl(ltrim($this->photo, '/'), time() + 3600);
		}
		else {
			return self::getUrlPath() . '/' . $this->photo;
		}
	}

	public function getPhotoThumb($width, $height, $returnFilePath = false, $fullSize = false)
	{
		/** @var PhotoThumbBehavior $photoThumbBehavior */
		$photoThumbBehavior = $this->getBehavior('PhotoThumbBehavior');

		if ($this->isOnCloud) {
			$tempPhoto = basename($this->photo);
			if (!file_exists($tempPhoto)) {
				Yii::$app->s3bucket->get(ltrim($this->photo, '/'), self::getTempPath() . DIRECTORY_SEPARATOR . $tempPhoto);
			}

			$originalThumbBehaviorPhotoPath = $photoThumbBehavior->photoPath;
			$originalPhoto = $this->photo;
			$this->photo = $tempPhoto;
			$photoThumbBehavior->photoPath = self::getTempPath();
			$thumb = $photoThumbBehavior->getPhotoThumb($width, $height, $returnFilePath, $fullSize);
			$this->photo = $originalPhoto;
			$photoThumbBehavior->photoPath = $originalThumbBehaviorPhotoPath;
			return $thumb;
		}
		else {
			return $photoThumbBehavior->getPhotoThumb($width, $height, $returnFilePath, $fullSize);
		}
	}

	public function getIsOnCloud()
	{
		// TODO Rewrite this, this condition is pretty weak
		return $this->photo[0] === '/';
	}

    static public function getPath()
    {
        return Yii::getAlias('@files/photo');
    }

    static public function getTempPath()
    {
        return Yii::getAlias('@files/photo/temp');
    }

    static public function getAllowedExtensions()
    {
        return ['jpg', 'jpeg', 'png', 'gif'];
    }

    static public function getMaxSize()
    {
        return isset(Yii::$app->params['journalPhoto.maxSize']) ? Yii::$app->params['journalPhoto.MaxSize'] : 5*1024*1024;
    }

    static public function getMaxWidth()
    {
        return isset(Yii::$app->params['journalPhoto.maxWidth']) ? Yii::$app->params['journalPhoto.maxWidth'] : 1024;
    }

    static public function getMaxHeight()
    {
        return isset(Yii::$app->params['journalPhoto.maxHeight']) ? Yii::$app->params['journalPhoto.maxHeight'] : 1024;
    }

    static public function getTempUrlPath()
    {
        return Yii::getAlias('@web/files/photo/temp');
    }

    static public function getUrlPath()
    {
        return Yii::getAlias('@web/files/photo');
    }

    /**
     * Возвращает форматированное описание.
     *
     * @param int $start
     * @param int $length
     * @return string
     */
    public function formatDescription($start, $length)
    {
        if (mb_strlen($this->description) <= $start) {
            return $this->description;
        }
        return mb_strimwidth($this->description, $start, $length);
    }
}