<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'CGIF' => $vendorDir . '/kartik-v/mpdf/classes/gif.php',
    'CGIFCOLORTABLE' => $vendorDir . '/kartik-v/mpdf/classes/gif.php',
    'CGIFFILEHEADER' => $vendorDir . '/kartik-v/mpdf/classes/gif.php',
    'CGIFIMAGE' => $vendorDir . '/kartik-v/mpdf/classes/gif.php',
    'CGIFIMAGEHEADER' => $vendorDir . '/kartik-v/mpdf/classes/gif.php',
    'CGIFLZW' => $vendorDir . '/kartik-v/mpdf/classes/gif.php',
    'Datamatrix' => $vendorDir . '/tecnickcom/tcpdf/include/barcodes/datamatrix.php',
    'INDIC' => $vendorDir . '/kartik-v/mpdf/classes/indic.php',
    'MYANMAR' => $vendorDir . '/kartik-v/mpdf/classes/myanmar.php',
    'OTLdump' => $vendorDir . '/kartik-v/mpdf/classes/otl_dump.php',
    'PDF417' => $vendorDir . '/tecnickcom/tcpdf/include/barcodes/pdf417.php',
    'PDFBarcode' => $vendorDir . '/kartik-v/mpdf/classes/barcode.php',
    'PclZip' => $vendorDir . '/pclzip/pclzip/pclzip.lib.php',
    'QRcode' => $vendorDir . '/tecnickcom/tcpdf/include/barcodes/qrcode.php',
    'SEA' => $vendorDir . '/kartik-v/mpdf/classes/sea.php',
    'SVG' => $vendorDir . '/kartik-v/mpdf/classes/svg.php',
    'TCPDF' => $vendorDir . '/tecnickcom/tcpdf/tcpdf.php',
    'TCPDF2DBarcode' => $vendorDir . '/tecnickcom/tcpdf/tcpdf_barcodes_2d.php',
    'TCPDFBarcode' => $vendorDir . '/tecnickcom/tcpdf/tcpdf_barcodes_1d.php',
    'TCPDF_COLORS' => $vendorDir . '/tecnickcom/tcpdf/include/tcpdf_colors.php',
    'TCPDF_FILTERS' => $vendorDir . '/tecnickcom/tcpdf/include/tcpdf_filters.php',
    'TCPDF_FONTS' => $vendorDir . '/tecnickcom/tcpdf/include/tcpdf_fonts.php',
    'TCPDF_FONT_DATA' => $vendorDir . '/tecnickcom/tcpdf/include/tcpdf_font_data.php',
    'TCPDF_IMAGES' => $vendorDir . '/tecnickcom/tcpdf/include/tcpdf_images.php',
    'TCPDF_IMPORT' => $vendorDir . '/tecnickcom/tcpdf/tcpdf_import.php',
    'TCPDF_PARSER' => $vendorDir . '/tecnickcom/tcpdf/tcpdf_parser.php',
    'TCPDF_STATIC' => $vendorDir . '/tecnickcom/tcpdf/include/tcpdf_static.php',
    'TTFontFile' => $vendorDir . '/kartik-v/mpdf/classes/ttfontsuni.php',
    'TTFontFile_Analysis' => $vendorDir . '/kartik-v/mpdf/classes/ttfontsuni_analysis.php',
    'UCDN' => $vendorDir . '/kartik-v/mpdf/classes/ucdn.php',
    'bmp' => $vendorDir . '/kartik-v/mpdf/classes/bmp.php',
    'cssmgr' => $vendorDir . '/kartik-v/mpdf/classes/cssmgr.php',
    'directw' => $vendorDir . '/kartik-v/mpdf/classes/directw.php',
    'grad' => $vendorDir . '/kartik-v/mpdf/classes/grad.php',
    'mPDF' => $vendorDir . '/kartik-v/mpdf/mpdf.php',
    'meter' => $vendorDir . '/kartik-v/mpdf/classes/meter.php',
    'mpdfform' => $vendorDir . '/kartik-v/mpdf/classes/mpdfform.php',
    'otl' => $vendorDir . '/kartik-v/mpdf/classes/otl.php',
    'tocontents' => $vendorDir . '/kartik-v/mpdf/classes/tocontents.php',
    'wmf' => $vendorDir . '/kartik-v/mpdf/classes/wmf.php',
);
