<?php

use common\rbac\Rights;
use yii\rbac\Item;

return \yii\helpers\ArrayHelper::merge(
    include 'auth_rights.php',
    [
        // Роли
        'guest' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Гость',
        ],
        'user' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Пользователь-семья',
            'children' => [
                'guest',
                // Доступы
                Rights::SHOW_GUIDE,
                Rights::SHOW_JOURNALS,
                Rights::SHOW_JOURNAL_SMART_SEARCH,
                Rights::SHOW_MY_JOURNAL_RECORDS,
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_FAMILY_JOURNAL,
                Rights::SHOW_TASKS_TO_ME,
                Rights::SHOW_FAMILIES_FOR_FAMILIES,
                Rights::SHOW_VISITS_TO_ME,
                Rights::EDIT_MY_JOURNAL,
                Rights::EDIT_MY_JOURNAL_PHOTO,
                Rights::SHOW_POINTS,
                Rights::DELETE_MY_OWN_COMMENT,
                Rights::EDIT_MY_OWN_COMMENT,
                Rights::CREATE_DIALOGS_WITH_SHOP_IN_MY_CITY,
                Rights::CREATE_TICKETS,
                //Rights::CREATE_FORUM_MESSAGE,
                Rights::SHOW_ADMINISTRATOR_INFO,
                Rights::ADD_COMMENT,
                Rights::GIVE_GIFT,
                // Уведомления
                Rights::SHOW_JOURNAL_ON_PUBLISHED_NOTIFICATION,
                Rights::SHOW_JOURNAL_ON_RETURN_TO_EDIT_NOTIFICATION,
                Rights::SHOW_TASK_ON_ADD_TO_ME_NOTIFICATION,
                Rights::SHOW_VISIT_ON_AGREEMENT_NOTIFICATION,
                Rights::SHOW_VISIT_AGREED_NOTIFICATION,
                Rights::SHOW_VISIT_CANCELED_NOTIFICATION,
                Rights::SHOW_MY_OWN_JOURNAL_ADD_COMMENT_NOTIFICATION,
                Rights::SHOW_ME_COMMENTED_JOURNAL_ADD_COMMENT_NOTIFICATION,
                Rights::SHOW_SEND_MESSAGE_NOTIFICATION,
                Rights::SHOW_USER_ON_CHANGE_CURATOR_NOTIFICATION,
                Rights::FILTER_FEED_USER,
                Rights::SHOW_POINTS_SPEND,
                Rights::SHOW_POINTS_EARNING,
            ],
        ],
        'shopModerator' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Магазин-модератор',
            'children' => [
                'guest',
                // Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_JOURNALS,
                Rights::SHOW_IN_MY_CITY_JOURNALS,
                Rights::SHOW_IN_MY_CITY_FAMILIES,
                Rights::SHOW_FAMILIES_PERSONAL_DATA,
                Rights::SHOW_IN_MY_CITY_TASKS,
                Rights::SHOW_IN_MY_CITY_VISITS,
                Rights::EDIT_OWN_TASKS,
                Rights::EDIT_OWN_VISITS,
                Rights::DELETE_IN_MY_CITY_COMMENT,
                Rights::CREATE_DIALOGS_WITH_FAMILY_IN_MY_CITY,
                Rights::CREATE_DIALOGS_WITH_ADMINISTRATOR,
                //Rights::CREATE_FORUM_SUB_THEME,
                //Rights::CREATE_FORUM_MESSAGES_THEME,
                //Rights::CREATE_FORUM_MESSAGE,
                Rights::SHOW_ADMINISTRATOR_INFO,
                Rights::ADD_COMMENT,
                Rights::EDIT_MY_OWN_COMMENT,
                Rights::SHOW_JOURNAL_SMART_SEARCH,
                Rights::SHOW_HELP_PRESENTATION,
                // Уведомления
                Rights::SHOW_NEW_USER_REGISTER_IN_MY_CITY_NOTIFICATION,
                Rights::SHOW_JOURNAL_ON_CHECK_IN_MY_CITY_NOTIFICATION,
                Rights::SHOW_JOURNAL_BY_OWN_TASK_ON_CHECK_NOTIFICATION,
                Rights::SHOW_VISIT_AGREED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_TIME_EDITED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_CANCELED_FAMILY_NOTIFICATION,
                Rights::SHOW_JOURNAL_ADD_IN_MY_CITY_COMMENT_NOTIFICATION,
                Rights::SHOW_ME_COMMENTED_JOURNAL_ADD_COMMENT_NOTIFICATION,
                Rights::SHOW_SEND_MESSAGE_NOTIFICATION,
                Rights::SHOW_MY_SUPERVISED_USER_DELETE_NOTIFICATION,
                Rights::FILTER_FEED_CURATOR,
            ],
        ],
        'shop' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Магазин-куратор',
            'children' => [
                'shopModerator',
                // Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_JOURNALS,
                Rights::SHOW_JOURNAL_SMART_SEARCH,
                Rights::SPEND_POINTS,
                Rights::SHOW_JOURNAL_ON_CHECK_COUNTER,
                Rights::SHOW_HELP_PRESENTATION,
                // Уведомления
                Rights::SHOW_USER_ON_CHANGE_CURATOR_NOTIFICATION,
                Rights::SHOW_JOURNAL_BY_TASK_ON_CHECK_BY_USER_CURATOR_NOTIFICATION,
                Rights::SHOW_FAMILY_LOCATIONS,
            ],
        ],
        'administrator' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Администратор',
            'children' => [
                'guest',
                //Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_ID_COLUMNS,
                Rights::SHOW_JOURNALS,
                Rights::EDIT_JOURNAL,
                Rights::FILTER_JOURNALS_BY_GOODS,
                Rights::SHOW_VISITS,
                Rights::EDIT_VISITS,
                Rights::SHOW_TASKS,
                Rights::EDIT_TASKS,
                Rights::SHOW_USERS,
                Rights::SHOW_DICTS,
                Rights::SHOW_SETTINGS,
                Rights::DELETE_COMMENT,
                Rights::EDIT_COMMENT,
                Rights::EDIT_HELP,
                Rights::SPEND_POINTS,
                Rights::EARN_POINTS,
                Rights::CREATE_DIALOGS,
                Rights::DELETE_FAMILIES,
                //Rights::CREATE_FORUM_THEME,
                //Rights::CREATE_FORUM_MESSAGE,
                Rights::FAMILY_SET_END_REPAIR_STATUS,
                Rights::FAMILY_SET_PROF_STATUS,
                Rights::SHOW_REPORTS,
                Rights::SHOW_ADMINISTRATOR_FULL_INFO,
                Rights::FAMILY_SET_CURATOR,
                Rights::ADD_COMMENT,
                Rights::READ_DIALOGS_BETWEEN_USER_AND_CURATOR,
                Rights::SHOW_JOURNAL_SMART_SEARCH,
                Rights::SHOW_HELP_PRESENTATION,
                Rights::SHOW_INVITES,
                // Уведомления
                Rights::SHOW_NEW_USER_REGISTER_NOTIFICATION,
                Rights::SHOW_USER_DELETE_NOTIFICATION,
                Rights::SHOW_JOURNAL_ON_CHECK_NOTIFICATION,
                Rights::SHOW_JOURNAL_BY_TASK_ON_CHECK_NOTIFICATION,
                Rights::SHOW_VISIT_AGREED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_TIME_EDITED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_CANCELED_FAMILY_NOTIFICATION,
                Rights::SHOW_JOURNAL_ADD_COMMENT_NOTIFICATION,
                Rights::SHOW_SEND_MESSAGE_NOTIFICATION,
                Rights::SHOW_FAMILY_POINTS_HISTORY,
                Rights::SHOW_FAMILY_LOCATIONS,
                Rights::FILTER_FEED_CURATOR,
            ],
        ],
        'marketing' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Маркетинг',
            'children' => [
                'guest',
                // Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_DICTS,
                Rights::SHOW_JOURNALS,
                Rights::FILTER_JOURNALS_BY_GOODS,
                Rights::SHOW_FAMILIES,
                Rights::SHOW_FAMILIES_PERSONAL_DATA,
                Rights::SHOW_SETTINGS,
                Rights::SHOW_TASKS,
                Rights::SHOW_VISITS,
                Rights::CREATE_DIALOGS,
                Rights::CREATE_DIALOGS_WITH_FAMILY,
                Rights::CREATE_DIALOGS_WITH_ADMINISTRATOR,
                //Rights::CREATE_FORUM_SUB_THEME,
                //Rights::CREATE_FORUM_MESSAGES_THEME,
                //Rights::CREATE_FORUM_MESSAGE,
                Rights::SHOW_ADMINISTRATOR_INFO,
                Rights::ADD_COMMENT,
                Rights::EDIT_MY_OWN_COMMENT,
                Rights::SHOW_HELP_PRESENTATION,
                // Уведомления
                Rights::SHOW_NEW_USER_REGISTER_NOTIFICATION,
                Rights::SHOW_JOURNAL_ON_CHECK_NOTIFICATION,
                Rights::SHOW_JOURNAL_BY_TASK_ON_CHECK_NOTIFICATION,
                Rights::SHOW_VISIT_AGREED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_TIME_EDITED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_CANCELED_FAMILY_NOTIFICATION,
                Rights::SHOW_JOURNAL_ADD_COMMENT_NOTIFICATION,
                Rights::SHOW_SEND_MESSAGE_NOTIFICATION,
                Rights::FILTER_FEED_USER,
            ],
        ],
        'all_lm' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Все сотрудники Леруа Мерлен',
            'children' => [
                'guest',
                // Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_DICTS,
                Rights::SHOW_JOURNALS,
                Rights::SHOW_JOURNAL_SMART_SEARCH,
                Rights::FILTER_JOURNALS_BY_GOODS,
                Rights::SHOW_FAMILIES,
                Rights::SHOW_SETTINGS,
                Rights::SHOW_TASKS,
                Rights::SHOW_VISITS,
                Rights::CREATE_DIALOGS,
                Rights::CREATE_DIALOGS_WITH_FAMILY,
                Rights::CREATE_DIALOGS_WITH_ADMINISTRATOR,
                //Rights::CREATE_FORUM_SUB_THEME,
                //Rights::CREATE_FORUM_MESSAGES_THEME,
                //Rights::CREATE_FORUM_MESSAGE,
                Rights::SHOW_ADMINISTRATOR_INFO,
                Rights::ADD_COMMENT,
                Rights::EDIT_MY_OWN_COMMENT,
                Rights::SHOW_HELP_PRESENTATION,
                // Уведомления
                Rights::SHOW_JOURNAL_ON_CHECK_NOTIFICATION,
                Rights::SHOW_JOURNAL_BY_OWN_TASK_ON_CHECK_NOTIFICATION,
                Rights::SHOW_VISIT_AGREED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_TIME_EDITED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_CANCELED_FAMILY_NOTIFICATION,
                Rights::SHOW_JOURNAL_ADD_COMMENT_NOTIFICATION,
                Rights::SHOW_SEND_MESSAGE_NOTIFICATION,
                Rights::FILTER_FEED_USER,
            ],
        ],
        'purchase' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Закупки',
            'children' => [
                'guest',
                // Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_JOURNALS,
                Rights::FILTER_JOURNALS_BY_GOODS,
                Rights::SHOW_FAMILIES,
                Rights::SHOW_FAMILIES_PERSONAL_DATA,
                Rights::SHOW_TASKS,
                Rights::EDIT_OWN_TASKS,
                Rights::SHOW_VISITS,
                Rights::EDIT_OWN_VISITS,
                Rights::CREATE_DIALOGS,
                Rights::CREATE_DIALOGS_WITH_FAMILY,
                Rights::CREATE_DIALOGS_WITH_ADMINISTRATOR,
                //Rights::CREATE_FORUM_SUB_THEME,
                //Rights::CREATE_FORUM_MESSAGES_THEME,
                //Rights::CREATE_FORUM_MESSAGE,
                Rights::SHOW_ADMINISTRATOR_INFO,
                Rights::ADD_COMMENT,
                Rights::EDIT_MY_OWN_COMMENT,
                Rights::SHOW_JOURNAL_SMART_SEARCH,
                Rights::SHOW_HELP_PRESENTATION,
                // Уведомления
                Rights::SHOW_JOURNAL_BY_OWN_TASK_ON_CHECK_NOTIFICATION,
                Rights::SHOW_VISIT_AGREED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_TIME_EDITED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_CANCELED_FAMILY_NOTIFICATION,
                Rights::SHOW_ME_COMMENTED_JOURNAL_ADD_COMMENT_NOTIFICATION,
                Rights::SHOW_SEND_MESSAGE_NOTIFICATION,
                Rights::FILTER_FEED_USER,
                Rights::SHOW_FAMILY_LOCATIONS,
            ],
        ],
        'viewJournalOnly' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Просмотр "Дневников"',
            'children' => [
                'guest',
                // Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_JOURNALS,
                Rights::SHOW_IN_MY_CITY_JOURNALS,
                Rights::SHOW_FAMILIES_FOR_FAMILIES,
                Rights::SHOW_HELP_PRESENTATION,
                // Уведомления
            ],
        ],
        'viewJournalOnlyAllCities' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Просмотр "Дневников" всех городов',
            'children' => [
                'guest',
                // Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_JOURNALS,
                Rights::SHOW_FAMILIES_FOR_FAMILIES,
                Rights::SHOW_HELP_PRESENTATION,
                // Уведомления
            ],
        ],
        'developer' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Администратор',
            'children' => [
                'administrator',
                // Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_JOURNALS,
                Rights::FAMILY_RESET_PASSWORD,
                Rights::USER_LOGIN_AS,
                Rights::USER_RESET_NOTIFICATIONS,
                Rights::SHOW_DEBUG_TOOLBAR,
            ],
        ],
        'marketing_plus' => [
            'type' => Item::TYPE_ROLE,
            'description' => 'Тестовая роль. Удалите меня',
            'children' => [
                'guest',
                // Доступы
                Rights::SHOW_MY_JOURNAL_FAVORITES,
                Rights::SHOW_JOURNALS,
                Rights::FILTER_JOURNALS_BY_GOODS,
                Rights::SHOW_FAMILIES,
                Rights::SHOW_FAMILIES_PERSONAL_DATA,
                Rights::SHOW_TASKS,
                Rights::EDIT_OWN_TASKS,
                Rights::SHOW_VISITS,
                Rights::EDIT_OWN_VISITS,
                Rights::CREATE_DIALOGS,
                Rights::CREATE_DIALOGS_WITH_FAMILY,
                Rights::CREATE_DIALOGS_WITH_ADMINISTRATOR,
                //Rights::CREATE_FORUM_SUB_THEME,
                //Rights::CREATE_FORUM_MESSAGES_THEME,
                //Rights::CREATE_FORUM_MESSAGE,
                Rights::SHOW_ADMINISTRATOR_INFO,
                Rights::ADD_COMMENT,
                Rights::EDIT_MY_OWN_COMMENT,
                Rights::SHOW_JOURNAL_SMART_SEARCH,
                Rights::SHOW_HELP_PRESENTATION,
                // Уведомления
                Rights::SHOW_JOURNAL_BY_OWN_TASK_ON_CHECK_NOTIFICATION,
                Rights::SHOW_VISIT_AGREED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_TIME_EDITED_FAMILY_NOTIFICATION,
                Rights::SHOW_VISIT_CANCELED_FAMILY_NOTIFICATION,
                Rights::SHOW_ME_COMMENTED_JOURNAL_ADD_COMMENT_NOTIFICATION,
                Rights::SHOW_SEND_MESSAGE_NOTIFICATION,
                Rights::FILTER_FEED_USER,
                Rights::SHOW_FAMILY_LOCATIONS,
            ],
        ],
    ]
);

