<?php
namespace frontend\models\forum;

use common\components\PersistSearchStateTrait;
use common\models\ForumMessage;
use common\models\ForumTheme;
use Exception;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\StringHelper;
use yii\log\Logger;

/**
 * Class ForumMessagesThemeForm
 * @package frontend\models\forum
 * @property ForumTheme $theme
 */
class ForumMessagesThemeForm extends Model
{
    public $theme = null;

    public $parent_theme_id;
    public $name;
    public $message;

    public function attributeLabels()
    {
        return [
            'name' => 'Название',
            'message' => 'Сообщение',
        ];
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return [
            ['name', 'required'],
            ['name', 'filter', 'filter' => 'trim'],
            ['name', 'string', 'max'=>250],

            ['message', 'required'],
            ['message', 'string', 'min'=>30],
            ['message', 'filter', 'filter' => 'trim'],
        ];
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios['create'] = ['name', 'message'];
        $scenarios['update'] = ['name', 'message'];
        return $scenarios;
    }

    public function init()
    {
        if ($this->theme != null) {
            $this->name = $this->theme->name;
            $this->message = $this->theme->getFirstMessage()->message;
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if ($this->validate()) {
            $tran = Yii::$app->getDb()->beginTransaction();
            try {
                if ($this->scenario == 'create') {
                    $this->theme = new ForumTheme([
                        'is_messages_theme' => 1,
                        'parent_id' => $this->parent_theme_id,
                        'name' => $this->name,
                    ]);
                }
                else {
                    $this->theme->name = $this->name;
                }

                if ($this->theme->save()) {
                    if ($this->scenario == 'create') {
                        $message = new ForumMessage([
                            'theme_id' => $this->theme->primaryKey,
                            'is_first' => 1,
                            'message' => $this->message,
                            'user_id' => Yii::$app->user->id,
                        ]);
                    } else {
                        $message = $this->theme->getFirstMessage();
                        $message->message = $this->message;
                    }

                    if ($message->save()) {
                        $tran->commit();
                        return true;
                    } else {
                        $this->addError('message', 'Возникла ошибка при сохранении сообщения [2]');
                        Yii::getLogger()->log(print_r($message->errors, true), Logger::LEVEL_ERROR);
                        $tran->rollBack();
                        return false;
                    }
                } else {
                    $this->addError('message', 'Возникла ошибка при сохранении сообщения [1]');
                    Yii::getLogger()->log(print_r($this->theme->errors, true), Logger::LEVEL_ERROR);
                    $tran->rollBack();
                    return false;
                }
            }
            catch (Exception $e) {
                Yii::getLogger()->log($e->getMessage(), Logger::LEVEL_ERROR);
                $tran->rollBack();
                return false;
            }
        }
    }

}